#!/bin/bash
#PBS -l nodes=01:ppn=16:xk
#PBS -l walltime=48:00:00
#PBS -N project_horse
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
#PBS -m bea
#PBS -M yd10@illinois.edu

cd ~/scratch/project/CS547Project


. /opt/modules/default/init/bash
module load bwpy/2.0.0-pre2
pip install dominate --user
pip install visdom --user

aprun -n 1 -N 1 python train.py --dataroot ./datasets/horse2zebra --name horses_cyclegan --model cycle_gan


